name: selfscape_app
description: A new Flutter project for SelfScape.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted to a common modern Flutter SDK range

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  mime: ^1.0.5

  cupertino_icons: ^1.0.6 # Often included in new Flutter projects

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Often included for linting

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
